[package]
name = "wanderdune"
version = "0.1.0"
authors = ["Benedikt Terhechte <terhechte@gmail.com>"]
build = "build.rs"

[dependencies]
askama = "0.6.4"
sha2 = "0.7.0"
rustbreak = "1.4.0"
ammonia = "1.1.0"

[build-dependencies]
askama = "0.6.4"